=== OlegFirsov/BullsCentre/bull.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="bull" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="bull">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="inbdrb" index-key="inb drb " primary="no" unique="yes" clustered="no"/>
<od:index index-name="PrimaryKey" index-key="id " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="bullKODR" index-key="kodr " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="id" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="kodr" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="kodrn" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="kodh" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="klihkab" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="inb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="markab" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="porb" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="linb" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="grb" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="drb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ddb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="mrb" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="klihkafb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="infb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="kodkatfb" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="klihkamb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="inmb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nummaxlactmb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="udmb" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float"/>
<xsd:element name="richmb" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="belokmb" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="klihkagfb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="inngfb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="kodkatgfb" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== OlegFirsov/BullsCentre/bull.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="bull.xsd" generated="2015-03-11T10:20:20">
<bull>
<id>3</id>
<kodr>43</kodr>
<kodrn>40</kodrn>
<kodh>10</kodh>
<klihkab>ШУТНИК</klihkab>
<inb>960</inb>
<porb>32</porb>
<linb>1</linb>
<grb>2</grb>
<drb>18.08.2006</drb>
<mrb>1</mrb>
<klihkafb>ЖУК</klihkafb>
<infb>369</infb>
<kodkatfb>2</kodkatfb>
<klihkamb>МАНЯ</klihkamb>
<inmb>258</inmb>
<nummaxlactmb>5</nummaxlactmb>
<udmb>100</udmb>
<richmb>0.5</richmb>
<belokmb>-0.3</belokmb>
<klihkagfb>ГАРИК</klihkagfb>
<inngfb>159</inngfb>
<kodkatgfb>2</kodkatgfb>
</bull>
<bull>
<id>5</id>
<kodr>16</kodr>
<kodrn>13</kodrn>
<kodh>19</kodh>
<klihkab>ЭДИП</klihkab>
<inb>1807</inb>
<porb>32</porb>
<linb>6</linb>
<grb>2</grb>
<drb>01.05.2003</drb>
<mrb>1</mrb>
<klihkafb>ТОР</klihkafb>
<infb>245</infb>
<kodkatfb>6</kodkatfb>
<klihkamb>ДАША</klihkamb>
<inmb>159</inmb>
<nummaxlactmb>1</nummaxlactmb>
<udmb>5500</udmb>
<richmb>3.2</richmb>
<belokmb>3.08</belokmb>
<klihkagfb>ДОН</klihkagfb>
<inngfb>569</inngfb>
<kodkatgfb>6</kodkatgfb>
</bull>
<bull>
<id>6</id>
<kodr>16</kodr>
<kodrn>16</kodrn>
<kodh>36</kodh>
<klihkab>ЭДАМ</klihkab>
<inb>700</inb>
<porb>30</porb>
<linb>1</linb>
<grb>2</grb>
<drb>10.10.2008</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>563</infb>
<kodkatfb>6</kodkatfb>
<klihkamb></klihkamb>
<inmb>589</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>4300</udmb>
<richmb>2.9</richmb>
<belokmb>0.5</belokmb>
<klihkagfb></klihkagfb>
<inngfb>248</inngfb>
<kodkatgfb>6</kodkatgfb>
</bull>
<bull>
<id>8</id>
<kodr>23</kodr>
<kodrn>9</kodrn>
<kodh>15</kodh>
<klihkab>ЮГ</klihkab>
<inb>8053</inb>
<porb>32</porb>
<linb>6</linb>
<grb>2</grb>
<drb>07.06.2002</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>157</infb>
<kodkatfb>15</kodkatfb>
<klihkamb></klihkamb>
<inmb>247</inmb>
<nummaxlactmb>0</nummaxlactmb>
<udmb>0</udmb>
<richmb>0</richmb>
<belokmb>0</belokmb>
<klihkagfb></klihkagfb>
<inngfb>247</inngfb>
<kodkatgfb>15</kodkatgfb>
</bull>
<bull>
<id>9</id>
<kodr>2</kodr>
<kodrn>55</kodrn>
<kodh>3</kodh>
<klihkab>ЮНКЕР</klihkab>
<inb>710101</inb>
<porb>32</porb>
<linb>1</linb>
<grb>2</grb>
<drb>20.10.1999</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>247</infb>
<kodkatfb>1</kodkatfb>
<klihkamb></klihkamb>
<inmb>367</inmb>
<nummaxlactmb>0</nummaxlactmb>
<udmb>0</udmb>
<richmb>0</richmb>
<belokmb>0</belokmb>
<klihkagfb></klihkagfb>
<inngfb>618</inngfb>
<kodkatgfb>1</kodkatgfb>
</bull>
<bull>
<id>10</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>ГОША</klihkab>
<inb>999999</inb>
<porb>32</porb>
<linb>1</linb>
<grb>2</grb>
<drb>10.10.2010</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>5645</infb>
<kodkatfb>4</kodkatfb>
<klihkamb></klihkamb>
<inmb>ИРА</inmb>
<nummaxlactmb>1</nummaxlactmb>
<udmb>2000</udmb>
<richmb>2.3</richmb>
<belokmb>0.5</belokmb>
<klihkagfb></klihkagfb>
<inngfb>РОМ</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>11</id>
<kodr>29</kodr>
<kodrn>16</kodrn>
<kodh>10</kodh>
<klihkab>ТОР</klihkab>
<inb>111111</inb>
<porb>32</porb>
<linb>1</linb>
<grb>2</grb>
<drb>21.07.2011</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>5645</infb>
<kodkatfb>4</kodkatfb>
<klihkamb></klihkamb>
<inmb>ИРА</inmb>
<nummaxlactmb>1</nummaxlactmb>
<udmb>2000</udmb>
<richmb>2.3</richmb>
<belokmb>0.5</belokmb>
<klihkagfb></klihkagfb>
<inngfb>РОМ</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>12</id>
<kodr>33</kodr>
<kodrn>17</kodrn>
<kodh>1</kodh>
<klihkab>ЯКОБ</klihkab>
<inb>7777777</inb>
<porb>1</porb>
<linb>9</linb>
<grb>1</grb>
<drb>10.10.2009</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>4568</infb>
<kodkatfb>13</kodkatfb>
<klihkamb></klihkamb>
<inmb>35345</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>5000</udmb>
<richmb>1.5</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>1248</inngfb>
<kodkatgfb>13</kodkatgfb>
</bull>
<bull>
<id>13</id>
<kodr>33</kodr>
<kodrn>17</kodrn>
<kodh>1</kodh>
<klihkab>ЯРД</klihkab>
<inb>333333</inb>
<porb>1</porb>
<linb>9</linb>
<grb>1</grb>
<drb>20.12.2012</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>4568</infb>
<kodkatfb>13</kodkatfb>
<klihkamb></klihkamb>
<inmb>35345</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>5000</udmb>
<richmb>1.5</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>1248</inngfb>
<kodkatgfb>13</kodkatgfb>
</bull>
<bull>
<id>14</id>
<kodr>32</kodr>
<kodrn>2</kodrn>
<kodh>14</kodh>
<klihkab>РИСК</klihkab>
<inb>666666666</inb>
<porb>2</porb>
<linb>55</linb>
<grb>2</grb>
<drb>20.12.2008</drb>
<mrb>1</mrb>
<klihkafb></klihkafb>
<infb>325346</infb>
<kodkatfb>4</kodkatfb>
<klihkamb></klihkamb>
<inmb>5534</inmb>
<nummaxlactmb>4</nummaxlactmb>
<udmb>3900</udmb>
<richmb>1.8</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>2357</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>15</id>
<kodr>31</kodr>
<kodrn>2</kodrn>
<kodh>5</kodh>
<klihkab>ЮГРА</klihkab>
<inb>1234567</inb>
<porb>2</porb>
<linb>55</linb>
<grb>2</grb>
<drb>10.10.2010</drb>
<mrb>3</mrb>
<klihkafb></klihkafb>
<infb>435345</infb>
<kodkatfb>13</kodkatfb>
<klihkamb></klihkamb>
<inmb>545435</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>2600</udmb>
<richmb>1.6</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>42342</inngfb>
<kodkatgfb>13</kodkatgfb>
</bull>
<bull>
<id>16</id>
<kodr>31</kodr>
<kodrn>2</kodrn>
<kodh>5</kodh>
<klihkab>КРАН</klihkab>
<inb>987654321</inb>
<porb>2</porb>
<linb>55</linb>
<grb>2</grb>
<drb>01.01.2008</drb>
<mrb>3</mrb>
<klihkafb></klihkafb>
<infb>435345</infb>
<kodkatfb>13</kodkatfb>
<klihkamb></klihkamb>
<inmb>545435</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>2600</udmb>
<richmb>1.6</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>42342</inngfb>
<kodkatgfb>13</kodkatgfb>
</bull>
<bull>
<id>17</id>
<kodr>33</kodr>
<kodrn>17</kodrn>
<kodh>1</kodh>
<klihkab>ТИГР</klihkab>
<inb>1245</inb>
<porb>2</porb>
<linb>55</linb>
<grb>2</grb>
<drb>06.06.2011</drb>
<mrb>3</mrb>
<klihkafb></klihkafb>
<infb>25656</infb>
<kodkatfb>22</kodkatfb>
<klihkamb></klihkamb>
<inmb>42342</inmb>
<nummaxlactmb>3</nummaxlactmb>
<udmb>3800</udmb>
<richmb>1.8</richmb>
<belokmb>0.9</belokmb>
<klihkagfb></klihkagfb>
<inngfb>235345</inngfb>
<kodkatgfb>22</kodkatgfb>
</bull>
<bull>
<id>18</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>абрикос</klihkab>
<inb>6326</inb>
<porb>32</porb>
<linb>5</linb>
<grb>2</grb>
<drb>13.04.1999</drb>
<mrb>36</mrb>
<klihkafb>а</klihkafb>
<infb>11</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>п</klihkamb>
<inmb>2</inmb>
<nummaxlactmb>5</nummaxlactmb>
<udmb>8888</udmb>
<richmb>3.45</richmb>
<belokmb>3.25</belokmb>
<klihkagfb>р</klihkagfb>
<inngfb>5</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>19</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Август</klihkab>
<inb>1613</inb>
<porb>30</porb>
<linb>9</linb>
<grb>1</grb>
<drb>26.09.1992</drb>
<mrb>36</mrb>
<klihkafb>в</klihkafb>
<infb>2</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>п</klihkamb>
<inmb>3</inmb>
<nummaxlactmb>6</nummaxlactmb>
<udmb>7777</udmb>
<richmb>3.46</richmb>
<belokmb>2.36</belokmb>
<klihkagfb>р</klihkagfb>
<inngfb>12</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>20</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Агент</klihkab>
<inb>308</inb>
<porb>32</porb>
<linb>6</linb>
<grb>2</grb>
<drb>28.05.2000</drb>
<mrb>36</mrb>
<klihkafb>п</klihkafb>
<infb>1</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>о</klihkamb>
<inmb>2</inmb>
<nummaxlactmb>5</nummaxlactmb>
<udmb>8888</udmb>
<richmb>3.45</richmb>
<belokmb>3.25</belokmb>
<klihkagfb>л</klihkagfb>
<inngfb>3</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>21</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Адажио</klihkab>
<inb>1876</inb>
<porb>30</porb>
<linb>5</linb>
<grb>11</grb>
<drb>01.06.2002</drb>
<mrb>36</mrb>
<klihkafb>л</klihkafb>
<infb>3</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>ю</klihkamb>
<inmb>4</inmb>
<nummaxlactmb>5</nummaxlactmb>
<udmb>9999</udmb>
<richmb>3.45</richmb>
<belokmb>3.26</belokmb>
<klihkagfb>д</klihkagfb>
<inngfb>8</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>22</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Юкас</klihkab>
<inb>6596</inb>
<porb>32</porb>
<linb>6</linb>
<grb>2</grb>
<drb>28.03.2002</drb>
<mrb>36</mrb>
<klihkafb>ф</klihkafb>
<infb>1</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>б</klihkamb>
<inmb>33</inmb>
<nummaxlactmb>5</nummaxlactmb>
<udmb>10000</udmb>
<richmb>3.88</richmb>
<belokmb>3.25</belokmb>
<klihkagfb>ю</klihkagfb>
<inngfb>25</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>24</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Адвокат</klihkab>
<inb>95</inb>
<porb>30</porb>
<linb>6</linb>
<grb>2</grb>
<drb>19.02.2003</drb>
<mrb>36</mrb>
<klihkafb>в</klihkafb>
<infb>1</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>ва</klihkamb>
<inmb>22</inmb>
<nummaxlactmb>8</nummaxlactmb>
<udmb>9999</udmb>
<richmb>3.89</richmb>
<belokmb>3.15</belokmb>
<klihkagfb>пр</klihkagfb>
<inngfb>111</inngfb>
<kodkatgfb>4</kodkatgfb>
</bull>
<bull>
<id>26</id>
<kodr>22</kodr>
<kodrn>61</kodrn>
<kodh>1</kodh>
<klihkab>Адлер</klihkab>
<inb>1033</inb>
<porb>32</porb>
<linb>1</linb>
<grb>2</grb>
<drb>07.04.1989</drb>
<mrb>36</mrb>
<klihkafb>о</klihkafb>
<infb>1</infb>
<kodkatfb>4</kodkatfb>
<klihkamb>ж</klihkamb>
<inmb>2</inmb>
<nummaxlactmb>8</nummaxlactmb>
<udmb>9999</udmb>
<richmb>3.45</richmb>
<belokmb>3.22</belokmb>
<klihkagfb>ж</klihkagfb>
<inngfb>2</inngfb>
<kodkatgfb>4</kodkatgfb>
