=== OlegFirsov/BullsCentre/lineage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="lineage" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="lineage">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="bullyearpor" index-key="idbull yearreport pordaughter " primary="no" unique="yes" clustered="no"/>
<od:index index-name="PrimaryKey" index-key="id " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="bulllineage" index-key="idbull " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="id" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="yearreport" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idbull" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="sper" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cena" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="kodkat" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
<xsd:element name="pordaughter" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== OlegFirsov/BullsCentre/lineage.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="lineage.xsd" generated="2015-03-11T10:20:39">
<lineage>
<id>157</id>
<yearreport>2012</yearreport>
<idbull>3</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>107</id>
<yearreport>2013</yearreport>
<idbull>3</idbull>
<sper>22.3</sper>
<cena>0</cena>
<kodkat>5</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>23</id>
<yearreport>2014</yearreport>
<idbull>3</idbull>
<sper>22.3</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>78</id>
<yearreport>2010</yearreport>
<idbull>3</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>91</id>
<yearreport>2011</yearreport>
<idbull>3</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>74</id>
<yearreport>2010</yearreport>
<idbull>5</idbull>
<sper>40.2</sper>
<cena>0</cena>
<kodkat>6</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>34</id>
<yearreport>2013</yearreport>
<idbull>5</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>92</id>
<yearreport>2011</yearreport>
<idbull>5</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>62</id>
<yearreport>2012</yearreport>
<idbull>5</idbull>
<sper>40.2</sper>
<cena>0</cena>
<kodkat>6</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>116</id>
<yearreport>2014</yearreport>
<idbull>5</idbull>
<sper>2.3</sper>
<cena>0</cena>
<kodkat>6</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>115</id>
<yearreport>2014</yearreport>
<idbull>5</idbull>
<sper>2.3</sper>
<cena>0</cena>
<kodkat>15</kodkat>
<pordaughter>29</pordaughter>
</lineage>
<lineage>
<id>93</id>
<yearreport>2011</yearreport>
<idbull>6</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>158</id>
<yearreport>2012</yearreport>
<idbull>6</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>79</id>
<yearreport>2010</yearreport>
<idbull>6</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>35</id>
<yearreport>2013</yearreport>
<idbull>6</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>24</id>
<yearreport>2014</yearreport>
<idbull>6</idbull>
<sper>22.7</sper>
<cena>0</cena>
<kodkat>6</kodkat>
<pordaughter>25</pordaughter>
</lineage>
<lineage>
<id>117</id>
<yearreport>2014</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>32</pordaughter>
</lineage>
<lineage>
<id>63</id>
<yearreport>2012</yearreport>
<idbull>8</idbull>
<sper>39.2</sper>
<cena>0</cena>
<kodkat>5</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>90</id>
<yearreport>2011</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>16</id>
<yearreport>2014</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>75</id>
<yearreport>2010</yearreport>
<idbull>8</idbull>
<sper>39.2</sper>
<cena>0</cena>
<kodkat>5</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>109</id>
<yearreport>2013</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>32</pordaughter>
</lineage>
<lineage>
<id>108</id>
<yearreport>2013</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>2</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>104</id>
<yearreport>2012</yearreport>
<idbull>8</idbull>
<sper>24.8</sper>
<cena>0</cena>
<kodkat>15</kodkat>
<pordaughter>32</pordaughter>
</lineage>
<lineage>
<id>25</id>
<yearreport>2014</yearreport>
<idbull>9</idbull>
<sper>15.3</sper>
<cena>0</cena>
<kodkat>4</kodkat>
<pordaughter>30</pordaughter>
</lineage>
<lineage>
<id>94</id>
<yearreport>2011</yearreport>
<idbull>9</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>37</id>
<yearreport>2013</yearreport>
<idbull>9</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>159</id>
<yearreport>2012</yearreport>
<idbull>9</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>80</id>
<yearreport>2010</yearreport>
<idbull>9</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>17</id>
<yearreport>2010</yearreport>
<idbull>10</idbull>
<sper>2.6</sper>
<cena>100</cena>
<kodkat>4</kodkat>
<pordaughter>32</pordaughter>
</lineage>
<lineage>
<id>95</id>
<yearreport>2011</yearreport>
<idbull>10</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>160</id>
<yearreport>2012</yearreport>
<idbull>10</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>27</id>
<yearreport>2014</yearreport>
<idbull>10</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>38</id>
<yearreport>2013</yearreport>
<idbull>10</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>96</id>
<yearreport>2011</yearreport>
<idbull>11</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>39</id>
<yearreport>2013</yearreport>
<idbull>11</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>28</id>
<yearreport>2014</yearreport>
<idbull>11</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>161</id>
<yearreport>2012</yearreport>
<idbull>11</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>81</id>
<yearreport>2010</yearreport>
<idbull>11</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>18</id>
<yearreport>2011</yearreport>
<idbull>12</idbull>
<sper>2.9</sper>
<cena>59</cena>
<kodkat>13</kodkat>
<pordaughter>1</pordaughter>
</lineage>
<lineage>
<id>162</id>
<yearreport>2012</yearreport>
<idbull>12</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>82</id>
<yearreport>2010</yearreport>
<idbull>12</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>40</id>
<yearreport>2013</yearreport>
<idbull>12</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>29</id>
<yearreport>2014</yearreport>
<idbull>12</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>83</id>
<yearreport>2010</yearreport>
<idbull>13</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>163</id>
<yearreport>2012</yearreport>
<idbull>13</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>30</id>
<yearreport>2014</yearreport>
<idbull>13</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>41</id>
<yearreport>2013</yearreport>
<idbull>13</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>97</id>
<yearreport>2011</yearreport>
<idbull>13</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>84</id>
<yearreport>2010</yearreport>
<idbull>14</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>31</id>
<yearreport>2014</yearreport>
<idbull>14</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>42</id>
<yearreport>2013</yearreport>
<idbull>14</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>98</id>
<yearreport>2011</yearreport>
<idbull>14</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>19</id>
<yearreport>2012</yearreport>
<idbull>14</idbull>
<sper>2.6</sper>
<cena>0</cena>
<kodkat>4</kodkat>
<pordaughter>1</pordaughter>
</lineage>
<lineage>
<id>164</id>
<yearreport>2012</yearreport>
<idbull>15</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>99</id>
<yearreport>2011</yearreport>
<idbull>15</idbull>
<sper>0</sper>
<cena>0</cena>
<kodkat>1</kodkat>
<pordaughter>99</pordaughter>
</lineage>
<lineage>
<id>20</id>
<yearreport>2014</yearreport>
<idbull>15</idbull>
<sper>2.9</sper>
<cena>150</cena>
<kodkat>4</kodkat>
